image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test  

install_dependencies:
  stage: build
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  needs: [install_dependencies]
  script:    
    - npm test