image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - debug
  - deploy

build:
  stage: build
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
  tags:
    - local-docker

test:
  stage: test
  needs: [build]
  script:    
    - npm test
  tags:
    - local-docker

deploy:
  stage: deploy
  needs: [build, test]
  script:
    - git fetch origin
    - git reset --hard origin/${CI_COMMIT_REF_NAME}
    - git config --global user.name "$GITLAB_USER_NAME"
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - npm version patch -m "Bump version to %s [skip ci]"
    - git remote set-url origin https://gitlab:${GIT_PUSH_TOKEN}@${CI_SERVER_HOST}/ben/bind9-rndc-node.git
    - git push origin HEAD:${CI_COMMIT_REF_NAME}    
    - echo "@ben:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc      
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - npm publish
  tags:
    - local-docker  

debug:
  stage: debug
  script:
    - git remote -v
    - git log --oneline -n 20
    - git tag
    - pwd
    - ls -la .git
  only:
    - main
  tags:
    - local-docker                