image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy
  
install_dependencies:
  stage: build
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/
  tags:
    - local-docker

test:
  stage: test
  needs: [install_dependencies]
  script:    
    - npm test
  tags:
    - local-docker

deploy:
  stage: deploy
  needs: [install_dependencies, test]
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  tags:
    - local-docker        